version: "3.9"

services:
  sveltekit:
    container_name: sveltekit
    build: .
    restart: always
    ports:
      - 5050:5050
    environment:
      PORT: 5050
      ORIGIN: "http://localhost:5050"

# networks:
#   default:
#     name: cloudflare
#     external: true